import type { AuditEventType } from "@/lib/audit/log-event";

export type AuditEventCategory = "access" | "content" | "friends" | "security" | "digital-legacy";

export const AUDIT_EVENT_TYPE_LABEL: Record<AuditEventType, string> = {
  login: "Accesso effettuato",
  logout: "Disconnessione",
  login_failed: "Tentativo di accesso fallito",
  mfa_challenge_failed: "Verifica a due fattori fallita",
  mfa_enrolled: "Autenticazione a due fattori attivata",
  mfa_removed: "Dispositivo di autenticazione rimosso",
  backup_codes_generated: "Codici di backup generati",
  document_created: "Contenuto aggiunto all'archivio",
  document_deleted: "Contenuto eliminato dall'archivio",
  asset_created: "Bene aggiunto",
  asset_deleted: "Bene eliminato",
  capsule_created: "Capsula creata",
  capsule_deleted: "Capsula eliminata",
  category_created: "Categoria creata",
  category_deleted: "Categoria eliminata",
  friend_added: "Amico aggiunto",
  vault_wiped: "Vault svuotato",
  ai_chat_used: "Domanda inviata all'assistente AI reale",
  trusted_device_registered: "Dispositivo fidato registrato",
  trusted_device_revoked: "Dispositivo fidato revocato",
  digital_legacy_reminder_sent: "Promemoria di inattività inviato",
  digital_legacy_grace_period_started: "Periodo di grazia iniziato",
  digital_legacy_awaiting_guardians: "Periodo di grazia scaduto, in attesa",
  digital_legacy_reset: "Eredità digitale annullata (accesso rilevato)",
};

export const AUDIT_EVENT_TYPE_ICON: Record<AuditEventType, string> = {
  login: "🔓",
  logout: "🔒",
  login_failed: "🚫",
  mfa_challenge_failed: "⚠️",
  mfa_enrolled: "🔐",
  mfa_removed: "🔓",
  backup_codes_generated: "🔑",
  document_created: "📄",
  document_deleted: "🗑️",
  asset_created: "💼",
  asset_deleted: "🗑️",
  capsule_created: "⏳",
  capsule_deleted: "🗑️",
  category_created: "🏷️",
  category_deleted: "🗑️",
  friend_added: "🤝",
  vault_wiped: "⚠️",
  ai_chat_used: "🤖",
  trusted_device_registered: "📱",
  trusted_device_revoked: "🚫",
  digital_legacy_reminder_sent: "💌",
  digital_legacy_grace_period_started: "⏳",
  digital_legacy_awaiting_guardians: "⏸️",
  digital_legacy_reset: "✅",
};

export const AUDIT_EVENT_TYPE_CATEGORY: Record<AuditEventType, AuditEventCategory> = {
  login: "access",
  logout: "access",
  login_failed: "access",
  mfa_challenge_failed: "security",
  mfa_enrolled: "security",
  mfa_removed: "security",
  backup_codes_generated: "security",
  document_created: "content",
  document_deleted: "content",
  asset_created: "content",
  asset_deleted: "content",
  capsule_created: "content",
  capsule_deleted: "content",
  category_created: "content",
  category_deleted: "content",
  friend_added: "friends",
  vault_wiped: "security",
  ai_chat_used: "security",
  trusted_device_registered: "security",
  trusted_device_revoked: "security",
  digital_legacy_reminder_sent: "digital-legacy",
  digital_legacy_grace_period_started: "digital-legacy",
  digital_legacy_awaiting_guardians: "digital-legacy",
  digital_legacy_reset: "digital-legacy",
};

export const AUDIT_EVENT_CATEGORY_LABEL: Record<AuditEventCategory, string> = {
  access: "Accessi",
  content: "Contenuti",
  friends: "Amici",
  security: "Sicurezza",
  "digital-legacy": "Eredità digitale",
};

export const AUDIT_EVENT_CATEGORIES: AuditEventCategory[] = [
  "access",
  "content",
  "friends",
  "security",
  "digital-legacy",
];
