import type { AuditEventType } from "@/lib/audit/log-event";

export type AuditEventCategory = "access" | "content" | "friends" | "security" | "digital-legacy";

export const AUDIT_EVENT_TYPE_LABEL: Record<AuditEventType, string> = {
  login: "Accesso effettuato",
  logout: "Disconnessione",
  login_failed: "Tentativo di accesso fallito",
  mfa_challenge_failed: "Verifica a due fattori fallita",
  mfa_enrolled: "Autenticazione a due fattori attivata",
  mfa_removed: "Dispositivo di autenticazione rimosso",
  backup_codes_generated: "Codici di backup generati",
  document_created: "Contenuto aggiunto all'archivio",
  document_deleted: "Contenuto eliminato dall'archivio",
  asset_created: "Bene aggiunto",
  asset_deleted: "Bene eliminato",
  capsule_created: "Capsula creata",
  capsule_deleted: "Capsula eliminata",
  category_created: "Categoria creata",
  category_deleted: "Categoria eliminata",
  friend_added: "Amico aggiunto",
  vault_wiped: "Vault svuotato",
  ai_chat_used: "Domanda inviata all'assistente AI reale",
  trusted_device_registered: "Dispositivo fidato registrato",
  trusted_device_revoked: "Dispositivo fidato revocato",
  digital_legacy_reminder_sent: "Promemoria di inattività inviato",
  digital_legacy_grace_period_started: "Periodo di grazia iniziato",
  digital_legacy_awaiting_guardians: "Periodo di grazia scaduto, in attesa",
  digital_legacy_reset: "Eredità digitale annullata (accesso rilevato)",
  digital_legacy_guardian_requested: "Verifica richiesta a un guardiano",
  digital_legacy_guardian_responded: "Un guardiano ha risposto",
  digital_legacy_guardians_confirmed: "Guardiani: irraggiungibilità confermata",
  digital_legacy_reset_by_guardian: "Eredità digitale annullata (un guardiano ha confermato che va tutto bene)",
  digital_legacy_formal_verification_started: "Verifica formale iniziata",
  digital_legacy_final_wait_started: "Attesa finale iniziata",
  digital_legacy_triggered: "Eredità digitale attivata: capsule aperte ai destinatari",
  friend_request_sent: "Richiesta di amicizia inviata",
  friend_request_accepted: "Richiesta di amicizia accettata",
  friend_request_rejected: "Richiesta di amicizia rifiutata",
  guardian_role_requested: "Richiesta di diventare guardiano inviata",
  guardian_role_accepted: "Richiesta di diventare guardiano accettata",
  guardian_role_rejected: "Richiesta di diventare guardiano rifiutata",
  guardian_role_revoked: "Guardiano rimosso",
  guardian_role_resigned: "Dimissioni da guardiano",
  proposal_accepted: "Proposta accettata",
  proposal_rejected: "Proposta rifiutata",
  proposal_undone: "Proposta annullata",
  dossier_created: "Fascicolo creato",
  dossier_deleted: "Fascicolo eliminato",
  document_trashed: "Contenuto spostato nel cestino",
  document_restored: "Contenuto ripristinato dal cestino",
  document_purged: "Contenuto eliminato per sempre",
};

export const AUDIT_EVENT_TYPE_ICON: Record<AuditEventType, string> = {
  login: "🔓",
  logout: "🔒",
  login_failed: "🚫",
  mfa_challenge_failed: "⚠️",
  mfa_enrolled: "🔐",
  mfa_removed: "🔓",
  backup_codes_generated: "🔑",
  document_created: "📄",
  document_deleted: "🗑️",
  asset_created: "💼",
  asset_deleted: "🗑️",
  capsule_created: "⏳",
  capsule_deleted: "🗑️",
  category_created: "🏷️",
  category_deleted: "🗑️",
  friend_added: "🤝",
  vault_wiped: "⚠️",
  ai_chat_used: "🤖",
  trusted_device_registered: "📱",
  trusted_device_revoked: "🚫",
  digital_legacy_reminder_sent: "💌",
  digital_legacy_grace_period_started: "⏳",
  digital_legacy_awaiting_guardians: "⏸️",
  digital_legacy_reset: "✅",
  digital_legacy_guardian_requested: "🛡️",
  digital_legacy_guardian_responded: "💬",
  digital_legacy_guardians_confirmed: "🚨",
  digital_legacy_reset_by_guardian: "✅",
  digital_legacy_formal_verification_started: "🔍",
  digital_legacy_final_wait_started: "⏳",
  digital_legacy_triggered: "🔓",
  friend_request_sent: "🤝",
  friend_request_accepted: "🤝",
  friend_request_rejected: "🙅",
  guardian_role_requested: "🛡️",
  guardian_role_accepted: "🛡️",
  guardian_role_rejected: "🙅",
  guardian_role_revoked: "🛡️",
  guardian_role_resigned: "🛡️",
  proposal_accepted: "✨",
  proposal_rejected: "🙅",
  proposal_undone: "↩️",
  dossier_created: "🗂️",
  dossier_deleted: "🗑️",
  document_trashed: "🗑️",
  document_restored: "♻️",
  document_purged: "🔥",
};

export const AUDIT_EVENT_TYPE_CATEGORY: Record<AuditEventType, AuditEventCategory> = {
  login: "access",
  logout: "access",
  login_failed: "access",
  mfa_challenge_failed: "security",
  mfa_enrolled: "security",
  mfa_removed: "security",
  backup_codes_generated: "security",
  document_created: "content",
  document_deleted: "content",
  asset_created: "content",
  asset_deleted: "content",
  capsule_created: "content",
  capsule_deleted: "content",
  category_created: "content",
  category_deleted: "content",
  friend_added: "friends",
  vault_wiped: "security",
  ai_chat_used: "security",
  trusted_device_registered: "security",
  trusted_device_revoked: "security",
  digital_legacy_reminder_sent: "digital-legacy",
  digital_legacy_grace_period_started: "digital-legacy",
  digital_legacy_awaiting_guardians: "digital-legacy",
  digital_legacy_reset: "digital-legacy",
  digital_legacy_guardian_requested: "digital-legacy",
  digital_legacy_guardian_responded: "digital-legacy",
  digital_legacy_guardians_confirmed: "digital-legacy",
  digital_legacy_reset_by_guardian: "digital-legacy",
  digital_legacy_formal_verification_started: "digital-legacy",
  digital_legacy_final_wait_started: "digital-legacy",
  digital_legacy_triggered: "digital-legacy",
  friend_request_sent: "friends",
  friend_request_accepted: "friends",
  friend_request_rejected: "friends",
  guardian_role_requested: "friends",
  guardian_role_accepted: "friends",
  guardian_role_rejected: "friends",
  guardian_role_revoked: "friends",
  guardian_role_resigned: "friends",
  proposal_accepted: "content",
  proposal_rejected: "content",
  proposal_undone: "content",
  dossier_created: "content",
  dossier_deleted: "content",
  document_trashed: "content",
  document_restored: "content",
  document_purged: "content",
};

export const AUDIT_EVENT_CATEGORY_LABEL: Record<AuditEventCategory, string> = {
  access: "Accessi",
  content: "Contenuti",
  friends: "Amici",
  security: "Sicurezza",
  "digital-legacy": "Eredità digitale",
};

export const AUDIT_EVENT_CATEGORIES: AuditEventCategory[] = [
  "access",
  "content",
  "friends",
  "security",
  "digital-legacy",
];
