-- "Novità" era ferma al 13 settembre (v. segnalazione utente) --- nessuna
-- riga scritta da quel punto in poi, pur essendo stato costruito
-- moltissimo (FASE 13, FASE C1, avvisi capsule, Eredità digitale,
-- riorganizzazione di Impostazioni, modello Amici v2). Backfill curato a
-- mano dal changelog di sviluppo (v. CHANGELOG.md, 2026-09-15 -> 17),
-- stesso criterio già usato per il backfill iniziale: solo ciò che
-- cambia davvero cosa puoi fare con Hinthial, in seconda persona --- non
-- ogni voce tecnica, non i bug fix, non ciò che è stato superato da una
-- modifica successiva prima ancora di essere raccontato qui (es. il
-- guardiano non collegato: comportamento sostituito il giorno dopo dal
-- nuovo modello di richieste, mai annunciato). Le 4 fasi di "Eredità
-- digitale" diventano una sola voce, che racconta il risultato finale
-- --- non il percorso incrementale, non interessante per chi legge qui.
insert into public.product_updates (title, description, published_on) values
($$Sblocca il vault con l'impronta o Face ID, non solo con la master password$$, $$In Impostazioni > Sicurezza puoi rendere fidato il dispositivo che stai usando --- richiede di nuovo la master password, una volta sola. Da quel momento, tornando su Hinthial da lì, sblocchi il vault con l'impronta digitale o Face ID invece di digitarla di nuovo. "Dimentica questo dispositivo" annulla la fiducia in un clic.$$, '2026-09-15'),
($$Sblocca un dispositivo nuovo con un QR, senza mai scrivere lì la password$$, $$Su un dispositivo che non hai ancora mai usato con Hinthial, scegli "Sblocca con un dispositivo fidato" al posto della master password: compare un QR code. Inquadralo con la fotocamera di un dispositivo già fidato e confermi lì con la master password --- il primo dispositivo si sblocca da solo, senza che tu l'abbia mai digitata.$$, '2026-09-15'),
($$Dispositivi fidati: l'elenco completo, gestibile da ovunque$$, $$In Impostazioni > Sicurezza trovi l'elenco di tutti i dispositivi che hai reso fidati --- nome, data di registrazione, ultimo accesso --- consultabile e revocabile da qualunque dispositivo, non solo da quello a cui si riferisce ogni riga.$$, '2026-09-15'),
($$Le tue capsule condivise diventano davvero apribili da chi le riceve$$, $$Se un amico con un vero account Hinthial è tra i destinatari di una capsula, quando la chiudi e la condividi la ritrova in "Condivise con me", con lo stesso countdown che vedi tu. Raggiunta la data di apertura, un tasto "Apri" gli mostra il contenuto --- decifrato sul suo dispositivo, mai sul tuo.$$, '2026-09-15'),
($$Un'email quando ricevi una capsula, popup di conferma, il tuo avatar al posto del menu ☰$$, $$Chi riceve una capsula condivisa riceve ora anche un'email di avviso, oltre a un popup la prima volta che apre la Dashboard. I messaggi di conferma (creato, chiuso, condiviso...) appaiono ora come popup che spariscono da soli, senza spostare il resto della pagina. Su smartphone, il tasto per aprire il menu è ora la tua foto o le tue iniziali, non più tre lineette.$$, '2026-09-16'),
($$Eredità digitale: decidi tu cosa succede alle tue capsule se un giorno non accedi più$$, $$Una nuova strategia, spenta di default e da attivare tu esplicitamente in Impostazioni: se non accedi per un periodo che scegli tu, arrivano promemoria via email; se il silenzio continua, i tuoi guardiani (persone di fiducia che hai indicato) vengono coinvolti per confermare se hanno tue notizie. Solo se anche loro confermano di non riuscire a raggiungerti, dopo un'ultima verifica e un'ultima attesa, le capsule che avevi già condiviso diventano leggibili a chi le doveva ricevere --- in ogni momento di questo percorso, un solo accesso tuo annulla tutto.$$, '2026-09-17'),
($$Impostazioni riorganizzate in aree più facili da scorrere$$, $$Le voci di Impostazioni, prima tutte allo stesso livello, sono ora raggruppate in aree --- Sicurezza, Privacy e dati, Personalizzazione --- più facili da scorrere a colpo d'occhio, sia da desktop che su smartphone. Stesso comportamento di sempre, solo più ordinato.$$, '2026-09-17'),
($$Amici: ogni nuovo contatto è già "Attivo"$$, $$Aggiungere un amico non richiede più un passo in più per "attivarlo": può essere subito destinatario di una capsula, senza doverlo segnare a mano come attivo.$$, '2026-09-17'),
($$Amici: un piccolo badge sulla foto dice chi è già su Hinthial$$, $$Quando un amico ha un account Hinthial collegato, un piccolo tondo blu con una "H" compare sull'angolo della sua foto o delle sue iniziali --- al posto della vecchia etichetta di testo.$$, '2026-09-17'),
($$Amici: l'amicizia diventa reciproca, e il Guardiano deve accettare$$, $$Aggiungere un contatto resta come sempre, privato. Se corrisponde a un account Hinthial esistente, puoi chiedergli l'amicizia: se accetta, comparirete entrambi come amici nella rispettiva lista. Solo un amico può diventare il tuo guardiano --- e solo se accetta esplicitamente una richiesta apposita, non più un interruttore che azionavi tu solo. Chi accetta trova una nuova pagina, "Protetti", con chi protegge e la possibilità di dimettersi quando vuole.$$, '2026-09-17');
